Fix HA router initialization exception
When an HA router initialization fails early, it can lead to:

 AttributeError: 'HaRouter' object has no attribute 'process_monitor'

Add init of 'self.process_monitor' in RouterInfo init code in
case we try and cleanup early.

Change-Id: Iddeaeef13adee10f7b130e3f9e584b6e9f037030
Closes-bug: #1735557
(cherry picked from commit c62d54d0c21fc4a760d2ac6501f9493137c5eb8a)