tests: don't allow oslo.config to autodiscover config files
oslo.config makes attempts to autodiscover configuration files using
find_config_files() helper. If e.g. /etc/neutron/neutron.conf exists,
and is not readable, the following test failure can be experienced:

oslo_config.cfg.ConfigFilesPermissionDeniedError: Failed to open some
config files: /etc/neutron/neutron.conf

Unit tests must not rely on any external state of the system and run
successfully no matter whether neutron is actually installed on the
system, or not.

Closes-Bug: #1442543
Change-Id: Ic90d8c40b2072fdda152703b84081719936b5f4e
(cherry picked from commit 54fc39308277d4aedc3e399286714d719ecacfbb)