Bug #1004584
When running ovs_quantum_agent in tunneling mode and a new tunnel_ip is added while
an agent is running the following exception below occurs. This causes the agent to
no longer function since it becomes caught in a loop.

ERROR:__main__:Main-loop Exception:
Traceback (most recent call last):
  File "ovs_quantum_agent.py", line 583, in daemon_loop
    self.manage_tunnels(tunnel_ips, old_tunnel_ips, db)
  File "ovs_quantum_agent.py", line 550, in manage_tunnels
    self.add_tun_br_flows_for_local_vlan(lv_obj)
AttributeError: 'OVSQuantumTunnelAgent' object has no attribute 'add_tun_br_flows_for_local_vlan'

Change-Id: Id03dc4a12a0114c8597cb90f4eabcdd3dc9b3f5c