Increase timeout in test_get_all_devices()
Although a wait_until_true() was added to this test, it
still occasionally fails. From the debug it looks like
the very next read of interfaces shows the one we were
waiting for was now present:

 AssertionError: MacVTap address: 4e:0f:75:b8:c8:c2,
    read devices: {'4e:0f:75:b8:c8:c2'}
  Device ens3, MAC: fa:16:3e:14:44:a1
  Device macvtap7b63baf3, MAC: 4e:0f:75:b8:c8:c2  ...

Increase the timeout to 10 seconds to see if it helps
the test become more stable.

Change-Id: Ie66163c0e8459c1e90ae3af375469f9996f0801c
Related-bug: #2012510