Remove import of 'imp' module
Use importlib.util module instead of imp, since it's
being deprecated:

  DeprecationWarning: the imp module is deprecated in favour of
  importlib; see the module's documentation for alternative uses

Had to change test setup to call super() first to get around a
config issue I was seeing locally, causing the entire class of
tests to fail:

  oslo_config.cfg.NoSuchOptError: no such option api_extensions_path
  in group [DEFAULT]

Closes-bug: #1981077

Change-Id: Ic171028a661c3f9f83f6758a57aaeab4450aa907