Fixed python3 failure in functional tests using net_helpers
.write expects a byte string in python3, while we were passing a
str. It worked in py2 but failed in py3 with:

TypeError: memoryview: a bytes-like object is required, not 'str'

Change-Id: I7f993a06bafa3cad4147f46d5d6dc10efeac3480