Move register_common_config_options call to DietTestCase
Running the quota unit tests generates this warning on
three tests:

 oslo_config.cfg.NoSuchOptError: no such option
  notify_nova_on_port_status_changes in group [DEFAULT]

Since this seems like it could be common for a number of
tests, move the register_common_config_options() call from
the BaseTestCase class to the DietTestCase class.

This could have alternatively been done in the setUp() code
in the TestQuotaDbApi() class.

Trivialfix

Change-Id: Ifd44dcfb57cdb8c0ebf976fd7c8da4009bdc1a3c