AttributeError: No such RPC function 'report_state'
This patch changes dhcp_agent_manager to be DhcpAgent instead of
DhcpAgentWithStateReport since not all plugins support DhcpAgentWithStateReport
and having this as the default breaks all current deployments that upgrade
source without changing their config files.

Fixes bug 1131446

Change-Id: I6415f85714b03e9bf59d597e8ec2397fedc92b02