Use bytes for python3 friendly os.write
Bytes not str. Otherwise we get
TypeError: a bytes-like object is required, not 'str'
in the metadata proxy and it dies.

Closes-Bug: #1661303
Change-Id: If6b6f19130c965436a637a03a4cf72203e0786b0