include python36-devel in bindep, for tests
as of https://review.opendev.org/#/c/751112/
py36 tests fail w/
  psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
  #include <Python.h>
           ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1

Change-Id: I84c5e7c64cb418f73ce84ea603e6d7025ff5c36f