Remove leading zeroes from an IP address
In python3.9, ipaddress.IPv4Interface does not support defining an
IP address with leading zeroes. E.g.:

>>> ipaddress.IPv4Interface('00.0.0.0/0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/ipaddress.py", line 1390, in __init__
    IPv4Address.__init__(self, addr)
  File "/usr/lib/python3.9/ipaddress.py", line 1307, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "/usr/lib/python3.9/ipaddress.py", line 1199, in
_ip_int_from_string
    raise AddressValueError("%s in %r" % (exc, ip_str)) from None
ipaddress.AddressValueError: Leading zeros are not permitted in '00' in
'00.0.0.0'

Change-Id: I29137b22c158e979e81be9e41464948aa99f5498
Closes-Bug: #1930222
(cherry picked from commit b141aed51296fd6564ccce18f907dc1913a4bc5b)