Fix wrong OS ENV type
If we set environment for Neutron tests in tox.ini, we may get
type error like:
TypeError: %d format: a number is required, not str

os.environ.get method will get string, not integer. This patch
fix it.

Change-Id: Ie71302b8e33586082ae8334e6317e30d382e893a