Fix bad i18n and fstrings interaction with flake8
Running 'tox -e pep8' on the neutron tree is showing
two identical warnings:

  NameError: name 'network_id' is not defined

These are coming from the metadata and OVN metadata code
that is trying to use both the i18n _() along with
f-strings.

Just change to use %s since this causes a flake8 failure.

TrivialFix

Change-Id: I8cc903bea1f6202749ee54dee3ee7c6450f324f1
(cherry picked from commit dae69e4ce69752ff56493052704ec95f9a42d685)