DVR: Fix bad arping call in centralized floating IP code
When the centralized floating IP code was added, the call
to send_ip_addr_adv_notif() had an incorrect argument,
leading to this failure in the l3-agent log:

TypeError: range() integer end argument expected, got ConfigOpts.

Closes-bug: #1717597
Change-Id: Ib0a5162912caac0508e19996fb13e431af39cfc4