DVR: Do not check HA state on DVR-only routers
Trying to check HA state on a DVR-only compute node
can trigger:

AttributeError: 'DvrLocalRouter' object has no attribute 'ha_state'

Also moved the mode assignment outside of the loops
since it only needs to be done once.

Co-Authored-By: Sean Redmond <sean.redmond1@gmail.com>
Closes-bug: #1691427
Change-Id: I3e48e06e76325939fbc9533b0198924bc96d600e
(cherry picked from commit b748f2e9b9892443cd4ae072f69a26f8af6da2d1)