Revert "Protect against non-determinstic sort"
This reverts commit 175bfe048283ae930b60b1cea87874d1fa1d10d6.

The change causes the following error if you're
unlucky enough to have such a marker column.

   ArgumentError: Only '=', '!=', 'is_()', 'isnot()' operators can be used with None/True/False

I saw test_floatingip_list_with_pagination failing,
where fixed_port_id of the marker was None.

Closes-Bug: #1656262
Change-Id: I6c32949d789f25d877d329ef0ae9d8650cb81acf