Use the correct input for OVN agent deletion
The key [1] is a list which is unhashable, therefore,
it can not be passed as dict key [2]. It causes
TypeError: unhashable type: 'list' exception.

[1] https://github.com/openstack/neutron/blob/24e70ea166b517df78ca720b279e2520720de1e7/neutron/plugins/ml2/drivers/ovn/mech_driver/ovsdb/ovsdb_monitor.py#L332
[2] https://github.com/openstack/neutron/blob/24e70ea166b517df78ca720b279e2520720de1e7/neutron/plugins/ml2/drivers/ovn/agent/neutron_agent.py#L281

Closes-bug: #2091071
Change-Id: I064d9b3e6cb72562a16030e1b31de45ddc8f487c
(cherry picked from commit ce6e2d87c52a11ec76a0f6fb7deb25a3dc26cf86)