Add more info when parsing config fails
Previously when parsed config contained wrong values, the message didn't
say what option is wrong. The message looked like:
TypeError: option values must be strings

This patch adds some info to the message so it says which option,
section and value is wrong. Example:

TypeError: option values must be strings: section DEFAULT,
option api_paste_config, value: None

Change-Id: Iaed040c3af9ab10292eeb49b0522ab09b23e29f7