TestSegmentHostMappingNoStore class is missing config
Trying to run the TestSegmentHostMappingNoStore class
unit tests fails if run standalone:

{0} neutron.tests.unit.extensions.test_segment.
    TestSegmentHostMappingNoStore.
    test_no_segmenthostmapping_when_disable_segment [0.001858s] ... FAILED

Error is about a missing option:

  oslo_config.cfg.NoSuchOptError: no such option service_plugins
    in group [DEFAULT]

It needs to register the common config options.

Trivialfix

Change-Id: I3e91d0019535b7d8f96d21fa4e255222c1db18d1