Fix AddrFormatError in DHCPv6 lease release code
A change that merged recently for DHCPv6 lease release
did not have the correct format for the lease file in
the unit test, so we started seeing these today from
the functional tests:

AddrFormatError: failed to detect a valid IP address from '[2003::2]'

We have to strip the brackets from IPs read from the
lease file.

https://review.openstack.org/#/c/301747/ was the culprit.

Closes-bug: 1619463

Change-Id: I0964fe9d00f8f3922041b12c352449e943b8f251